### ISSUE TITLE
Crash on input while editing files with Markdown extension

### ISSUE THREAD

**Issue by int3l** [asottile/babi#121] opened 2021-01-09 17:52 UTC
Software versions:

Python: Python 3.9.0
Windows 10: 20H2

```text
Package           Version
----------------- -------
babi              0.0.19
babi-grammars     0.0.21
cffi              1.14.4
cfgv              3.2.0
filelock          3.0.12
onigurumacffi     1.0.0
pycparser         2.20
PyYAML            5.3.1
six               1.15.0
toml              0.10.2
typed-ast         1.4.2
typing-extensions 3.7.4.3
windows-curses    2.2.0
```

Command:

```bash
babi t.md
```

Input:

~~~text
```t
~~~

As soon as this sequence of characters is entered, babi crashes with:

```console
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "Z:\anthonywritescode\explains\venv\Scripts\babi.exe\__main__.py", line 7, in <module>
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\main.py", line 152, in main
    return c_main(stdscr, filenames, positions, stdin, perf)
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\main.py", line 57, in c_main
    res = _edit(screen, stdin)
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\main.py", line 29, in _edit
    screen.draw()
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\screen.py", line 262, in draw
    self.file.draw(self.stdscr, self.margin)
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\file.py", line 861, in draw
    file_hl.highlight_until(self.buf, self.buf.file_y + to_display)
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\hl\syntax.py", line 119, in highlight_until
    state, regions = self._hl(state, lines[i], i == 0)  # type: ignore
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\hl\syntax.py", line 63, in _hl_uncached
    new_state, regions = highlight_line(
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\highlight.py", line 782, in highlight_line
    search_res = state.cur.rule.search(
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\highlight.py", line 485, in search
    return _do_regset(idx, match, self, compiler, state, pos)
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\highlight.py", line 363, in _do_regset
    target_rule = compiler.compile_rule(rule.u_rules[idx])
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\highlight.py", line 663, in compile_rule
    ret = self._c_rules[rule] = self._compile_rule(grammar, rule)
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\highlight.py", line 642, in _compile_rule
    regs, rules = self._patterns(grammar, rule.patterns)
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\highlight.py", line 595, in _patterns
    tmp_regs, tmp_rules = self._include(
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\highlight.py", line 578, in _include
    grammar = self._grammars.grammar_for_scope(s)
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\highlight.py", line 708, in grammar_for_scope
    raw = self._raw_for_scope(scope)
  File "Z:\anthonywritescode\explains\venv\lib\site-packages\babi\highlight.py", line 690, in _raw_for_scope
    grammar_path = self._scope_to_files.pop(scope)
KeyError: 'source.perl'
```

Workaround: Enter different sequence and then remove the unneeded characters :)
For example:
~~~text
```atext -> ```text
~~~

**Comment by asottile** [comment] 2021-01-09 18:15
dupe of asottile/babi-grammars#11

**Closed by asottile** 2021-01-09 18:15 UTC
